spring.application.name=NorthlakeBridgeVentures

# 1. The Connection URL (Get the Endpoint from RDS Console)
spring.datasource.url=jdbc:mysql://your-db-instance.xxxx.us-east-1.rds.amazonaws.com:3306/pocdb

# 2. Database Credentials
spring.datasource.username=admin
spring.datasource.password=${DB_PASSWORD}

# 3. Driver and Hibernate Settings
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 4. Hibernate Auto-Table Creation (Useful for POC)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Test